ALTER TABLE jn_privilege modify action_name varchar(20) not null comment '方法名称';
ALTER TABLE jn_privilege modify module_name varchar(20) not null comment '模块名称';
ALTER TABLE jn_privilege modify	controller_name varchar(20) not null comment '控制器名称';
ALTER TABLE jn_goods add is_promote tinyint unsigned not null default '0' comment '是否促销';
ALTER TABLE jn_goods modify brand_id smallint unsigned comment '品牌的id';
ALTER TABLE jn_goods modify promote_start_time int unsigned not null default '0' comment '促销开始时间';
ALTER TABLE jn_goods modify promote_end_time int unsigned not null default '0' comment '促销结束时间';
ALTER TABLE jn_goods modify jifen int unsigned not null default '0' comment '赠送积分';
ALTER TABLE jn_goods modify	jyz int unsigned not null default '0' comment '赠送经验值';
ALTER TABLE jn_goods modify	goods_desc longtext not null default '' comment '商品描述';
ALTER TABLE jn_member_level add rate tinyint unsigned not null default '100' comment '商品折扣率,按百分比算';
ALTER TABLE jn_goods_number modify goods_number int unsigned not null default '0' comment '库存量';
ALTER TABLE jn_member add jifen int unsigned not null default '0' comment '积分';
ALTER TABLE jn_member add jyz int unsigned not null default '0' comment '经验值';
ALTER TABLE jn_member modify id mediumint unsigned not null auto_increment comment '会员id';
ALTER TABLE jn_goods_number engine=innodb;
ALTER TABLE jn_order engine=innodb;
ALTER TABLE jn_order_goods engine=innodb;
ALTER TABLE jn_category add search_attr_id varchar(100) not null default '' comment '筛选ID，多个用逗号隔开';
